name: CI build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build artifacts and deploy preview
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          fetch-depth: 0

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version-file: './master/package.json'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build webUI
        run: |
          cd master
          yarn install
          yarn build
          yarn build-zip
          yarn build-md5
          ls buildZip

      - name: Generate Tag Name
        id: GenTagName
        run: |
          cd master/build
          genTag="r$(git rev-list HEAD --count)"
          echo "$genTag"
          echo "::set-output name=value::$genTag"

      # Legacy preview steps removed (Suwayomi/Suwayomi-WebUI-preview not accessible)
